import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Aside from "@/components/Aside";

const robotoSans = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans.className} antialiased`}
      >
        <Header />
      <div className="flex items-start max-w-[1100px] m-auto t-[90px] gap-5 max-h-screen h-full pt-[170px] px-3">
      <Aside />
        {children}
      </div>
      </body>
    </html>
  );
}
